import type { Metadata } from 'next'
import '../assets/globals.scss'
import Footer from '@/widgets/footer/Footer'
import Header from '@/widgets/header/Header'
import ApiProvider from '@/features/api-provider/ApiProvider'

export const metadata: Metadata = {
	title: 'XWEAR - магазин обуви. одежды и акссесуаров',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<ApiProvider>
					<Header />
					<main>{children}</main>
					<Footer />
				</ApiProvider>
			</body>
		</html>
	)
}
